type crash {
  crash_id: 
  fatalities: 
  crash_sk: 
  crashTypeIsCrashType: crash_type @relationship(type: "CRASH_TYPE_IS", direction: OUT)
  inDateDate: date @relationship(type: "IN_DATE", direction: OUT)
  inLgaLga: lga @relationship(type: "IN_LGA", direction: OUT)
  inEventHoliday: holiday @relationship(type: "IN_EVENT", direction: OUT)
  inRoadTypeRoadType: road_type @relationship(type: "IN_ROAD_TYPE", direction: OUT)
  involvementIsInvolvement: involvement @relationship(type: "INVOLVEMENT_IS", direction: OUT)
  inTimeTime: time @relationship(type: "IN_TIME", direction: OUT)
  inSpeedLimitSpeedLimit: speed_limit @relationship(type: "IN_SPEED_LIMIT", direction: OUT)
  fatalityInCrash: fatality @relationship(type: "IN_CRASH", direction: IN)
}

type state {
  state: 
  state_sk: 
  hasLgaLga: lga @relationship(type: "HAS_LGA", direction: OUT)
  sa4InState: sa4 @relationship(type: "IN_STATE", direction: IN)
}

type date {
  year: 
  month: 
  dayweek: 
  day_of_week: 
  date_sk: 
  crashInDate: crash @relationship(type: "IN_DATE", direction: IN)
}

type crash_type {
  crash_type: 
  crash_type_sk: 
  crashCrashTypeIs: crash @relationship(type: "CRASH_TYPE_IS", direction: IN)
}

type fatality {
  age: 
  fatality_sk: 
  ageIsAgeGroup: age_group @relationship(type: "AGE_IS", direction: OUT)
  genderIsGender: gender @relationship(type: "GENDER_IS", direction: OUT)
  roadUserIsRoadUser: road_user @relationship(type: "ROAD_USER_IS", direction: OUT)
  inCrashCrash: crash @relationship(type: "IN_CRASH", direction: OUT)
}

type lga {
  lga: 
  lga_sk: 
  crashInLga: crash @relationship(type: "IN_LGA", direction: IN)
  stateHasLga: state @relationship(type: "HAS_LGA", direction: IN)
  inSa4Sa4: sa4 @relationship(type: "IN_SA4", direction: OUT)
  inNraNra: nra @relationship(type: "IN_NRA", direction: OUT)
}

type holiday {
  easter: 
  christmas: 
  holiday_sk: 
  crashInEvent: crash @relationship(type: "IN_EVENT", direction: IN)
}

type age_group {
  age_group: 
  age_group_sk: 
  fatalityAgeIs: fatality @relationship(type: "AGE_IS", direction: IN)
}

type gender {
  gender: 
  gender_sk: 
  fatalityGenderIs: fatality @relationship(type: "GENDER_IS", direction: IN)
}

type road_user {
  road_user: 
  road_user_sk: 
  fatalityRoadUserIs: fatality @relationship(type: "ROAD_USER_IS", direction: IN)
}

type road_type {
  road_type: 
  road_type_sk: 
  crashInRoadType: crash @relationship(type: "IN_ROAD_TYPE", direction: IN)
}

type involvement {
  bus: 
  heavy_rigid_truck: 
  articulated_truck: 
  involvement_sk: 
  crashInvolvementIs: crash @relationship(type: "INVOLVEMENT_IS", direction: IN)
}

type time {
  hour: 
  time_of_day: 
  time_sk: 
  crashInTime: crash @relationship(type: "IN_TIME", direction: IN)
}

type speed_limit {
  speed_limit: 
  speed_limit_sk: 
  crashInSpeedLimit: crash @relationship(type: "IN_SPEED_LIMIT", direction: IN)
}

type nra {
  nra: 
  nra_sk: 
  lgaInNra: lga @relationship(type: "IN_NRA", direction: IN)
}

type sa4 {
  sa4: 
  sa4_sk: 
  lgaInSa4: lga @relationship(type: "IN_SA4", direction: IN)
  inStateState: state @relationship(type: "IN_STATE", direction: OUT)
}